// src/options/Options.tsx
import { useStorageLocal } from '~/hooks/useStorageLocal'
import IconSliders from '~icons/pixelarticons/sliders'
import IconZap from '~icons/pixelarticons/zap'

export default function Options() {
  const [storageDemo, setStorageDemo] = useStorageLocal<string>(
    'webext-demo',
    'Storage Demo'
  )

  return (
    <main className="text-center py-10 px-4 text-gray-700 dark:text-gray-200">
      <IconSliders className="mx-2 text-2xl icon-btn" />
      <div>Options</div>
      <p className="mt-2 opacity-50">This is the options page</p>

      <input
        className="border rounded border-gray-400 mt-2 py-1 px-2"
        value={storageDemo}
        onChange={(event) => setStorageDemo(event.target.value)}
      />

      <div className="mt-4">
        Powered by Vite <IconZap className="align-middle" />
      </div>
    </main>
  )
}

// src/options/Options.vue
<template>
  <main class="px-4 py-10 text-center text-gray-700 dark:text-gray-200">
    <pixelarticons-sliders class="icon-btn mx-2 text-2xl" />
    <div>Options</div>
    <p class="mt-2 opacity-50">This is the options page</p>

    <input
      v-model="storageDemo"
      class="border border-gray-400 rounded px-2 py-1 mt-2"
    />

    <div class="mt-4">
      Powered by Vite <pixelarticons-zap class="align-middle" />
    </div>
  </main>
</template>

<script setup lang="ts">
import { storageDemo } from '~/logic/storage'
</script>
